### ISSUE TITLE
Content Changes

### ISSUE THREAD

**Issue by abhinavtripathy** [team-eyespace/Eyespace-website#6]
- Subtitle needs improvement(Delivering solutions for the differently-abled
and the elderly") 
- Take a look at the presentation for Google Next to change mission and About us, revamp text on website.
- Grammar errors in timeline content
- Beta testing timeline logo to be changed, needs to look more like Beta logo.

**Comment by AdiNar1106** [comment]
Content work phase 1 complete, ready for review
